Repository codeit-fe-17-team4/Taskify, pull requests merged in 2025-09, with the labels that each got.

#40 [공통] dashboard-header, side-menu API 연동 및 데이터 페칭 custom hook 작업
  eslint.config.ts
  src/components/mydashboard/create-newboard-modal.tsx
  src/components/ui/dashboard-header/header-profile-dropdown.tsx
  src/components/ui/dashboard-header/index.tsx
  src/components/ui/dashboard-header/profile-list.tsx
  src/components/ui/modal/modal-portal.tsx
  src/components/ui/side-menu/dashboard-list.tsx
  src/components/ui/side-menu/dot.tsx
  src/components/ui/side-menu/index.tsx
  src/hooks/useAsync.ts
  src/hooks/useIsBreakPoint.ts
  src/lib/cards/type.ts
  src/lib/comments/type.ts
  src/lib/dashboards/type.ts
  src/lib/invitations/type.ts
  src/lib/members/type.ts
  src/lib/users/type.ts
  src/pages/_document.tsx
  src/pages/mydashboard/index.tsx
  src/utils/dashboard-color.ts
Labels: ✨ 기능

#48 feat: invite-modal 기능 및 에러처리, 프로필 리스트 색상 기능
  src/components/mydashboard/invite-member-modal.tsx
  src/components/mydashboard/type.ts
  src/components/ui/dashboard-header/index.tsx
  src/components/ui/dashboard-header/invite-member-form.tsx
  src/components/ui/dashboard-header/invite-member-modal.tsx
  src/components/ui/dashboard-header/profile-list.tsx
  src/hooks/useAsync.ts
  src/lib/custom-error.ts
  src/lib/custom-fetch.ts
  src/lib/dashboards/api.ts
Labels: ✨ 기능

#47 feat: [dashboard] API 연동, DnD 및 댓글 무한스크롤 기능 추가
  next.config.ts
  package-lock.json
  package.json
  src/components/dashboard/column-layout.tsx
  src/components/dashboard/column-task-card.tsx
  src/components/dashboard/dashboard-column.tsx
  src/components/dashboard/infinite-comment-list.tsx
  src/components/dashboard/modal/create-column-modal.tsx
  src/components/dashboard/modal/create-task-form.tsx
  src/components/dashboard/modal/create-task-modal.tsx
  src/components/dashboard/modal/edit-task-form.tsx
  src/components/dashboard/modal/edit-task-modal.tsx
  src/components/dashboard/modal/manage-column-modal.tsx
  src/components/dashboard/modal/task-detail-modal.tsx
  src/components/dashboard/sortable-task-card.tsx
  src/components/dashboard/type.ts
  src/components/ui/chip/chip-profile.tsx
  src/components/ui/dropdown/list.tsx
  src/hooks/useCursorInfiniteScroll.ts
  src/hooks/useDashboardData.ts
  src/hooks/useTaskHandlers.ts
  src/lib/cards/api.ts
  src/lib/cards/interface.ts
  src/lib/cards/type.ts
  src/lib/columns/api.ts
  src/lib/comments/api.ts
  src/lib/constants.ts
  src/lib/custom-fetch.ts
  src/lib/dashboard-mock-data.ts
  src/lib/members/api.ts
  src/lib/validation/rules.ts
  src/pages/dashboard/[dashboardId]/index.tsx
  src/styles/globals.css
  tatus
Labels: 🛠️ 리팩토링, ✨ 기능

#49 feat: chip-profile의 color가 userId에 따라 고정되게끔 변경 + task-form 태그 한글 입력 버그 해결
  next.config.ts
  package-lock.json
  package.json
  src/components/auth/AuthButton.tsx
  src/components/auth/UnifiedModal.tsx
  src/components/dashboard/add-column-button.tsx
  src/components/dashboard/add-task-button.tsx
  src/components/dashboard/column-header.tsx
  src/components/dashboard/column-task-card.tsx
  src/components/dashboard/modal/create-task-form.tsx
  src/components/dashboard/modal/edit-task-form.tsx
  src/components/dashboard/modal/task-detail-modal.tsx
  src/components/dashboard/skeleton/card.tsx
  src/components/dashboard/skeleton/column.tsx
  src/components/edit-dashboard/edit-dashboard-form.tsx
  src/components/edit-dashboard/member-list.tsx
  src/components/home/Header.tsx
  src/components/home/Hero.tsx
  src/components/mydashboard/dashboard-list.tsx
  src/components/ui/animated-number.tsx
  src/components/ui/button/button.tsx
  src/components/ui/chip/chip-profile.tsx
  src/components/ui/dashboard-header/header-profile-dropdown.tsx
  src/components/ui/dashboard-header/index.tsx
  src/components/ui/dashboard-header/profile-list.tsx
  src/components/ui/dashboard-header/skeleton.tsx
  src/components/ui/dropdown/item.tsx
  src/components/ui/dropdown/list.tsx
  src/components/ui/loading-circle.tsx
  src/components/ui/modal/modal-button.tsx
  src/components/ui/side-menu/dashboard-list.tsx
  src/components/ui/side-menu/index.tsx
  src/components/ui/side-menu/skeleton.tsx
  src/hooks/useDashboardData.ts
  src/hooks/useTaskHandlers.ts
  src/middleware.ts
  src/pages/dashboard/[dashboardId]/edit.tsx
  src/pages/dashboard/[dashboardId]/index.tsx
  src/pages/login/index.tsx
  src/pages/mydashboard/index.tsx
  src/pages/mypage/index.tsx
  src/pages/signup/index.tsx
  src/styles/globals.css
  src/utils/profile-color.ts
Labels: 👾 버그, ✨ 기능
